### ISSUE TITLE
Providing training infrastructure for users

### ISSUE THREAD

**Issue by saanikat** [databio/bedms#24]
For a user to be able to train their own datasets:
1. Training scripts (user friendly) for all models.
2. Additions to `attr_standardizer` to be able to fetch the users' models from HuggingFace.
3. Documentation

**Comment by nleroy917** [comment]
Maybe relevant: https://github.com/databio/geniml_dev/issues/166

**Comment by ClaudeHu** [comment]
trainer object for `text2bed` : [genimlv.text2bed.vec2vec](https://github.com/databio/geniml_dev/blob/dev_search/geniml/text2bed/vec2vec/training.py) (it may be messy for a while since it is under update for alternative training methods, also I have plan to introduce `lightning` modules to `text2bed` according to suggestion from @nleroy917 )

reference code: [music text representation](https://github.com/seungheondoh/music-text-representation/blob/5e54e0dfdf2bcbce7be693b363aa7e4b4802b740/mtr/contrastive/train.py#L224), [musiclm](https://github.com/lucidrains/musiclm-pytorch/blob/4a78b41feab25d0ad0f4a1be8ea46b0aaf83d23a/musiclm_pytorch/trainer.py#L147)

**Comment by nleroy917** [comment]
Also, [`wandb`](https://github.com/wandb/wandb) has been absolutely amazing for experiment tracking. I even started a `databio-ml` team: https://wandb.ai/databio-ml

`databio` was taken...

`lightning` is great because it gets rid of all headaches around GPU/slurm/DDP
`wandb` is great because it gets rid of all headaches around tracking model progress

I also have a lot of fun stuff I've learned about training models with `slurm` and being able to kill things prematurely and gracefully.

**Comment by saanikat** [comment]
Likely solved with the new PR #25 
Detailed documentation will be added to [ bedbase docs](https://docs.bedbase.org/)
